runtime: python310

entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10


runtime_config:
  python_version: 3.10

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: smailsql123
  CLOUD_SQL_DATABASE_NAME: smail
  CLOUD_SQL_CONNECTION_NAME: quantum-boulder-381913:asia-southeast2:smailsql

